version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        DATABASE_URL: 'postgresql://myapp:mypassword@localhost:9112/absence-management?schema=public'
        NUXT_PUBLIC_BASE_URL: 'http://localhost:3000'
    working_dir: /app
    ports:
      - '3000:3000'
    volumes:
      - ./data/uploads:/app/public/uploads
    environment:
      DATABASE_URL: 'postgresql://myapp:mypassword@db:5432/absence-management?schema=public'
      NUXT_ACCESS_TOKEN_EXPIRES_IN: '90d'
      NUXT_ACCESS_TOKEN_SECRET_KEY: '5f834cf2-46ce-4e1f-9204-5a22d3f7a63b'
      NUXT_PUBLIC_BASE_URL: 'http://localhost:3000'
    depends_on:
      - db
  db:
    image: 'postgres:15.3-alpine3.18'
    ports:
      - '9112:5432'
    environment:
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./data/pg:/var/lib/postgresql/data